#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -x "/usr/bin/systemctl" ]; then
            if systemctl is-active --quiet mapecd 2>/dev/null; then
                systemctl stop mapecd
            fi
            if systemctl is-enabled --quiet mapecd 2>/dev/null; then
                systemctl disable mapecd
            fi
        fi
    ;;
esac

#DEBHELPER#
